/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.CuentaAhorros;
import model.CuentaBancaria;
import service.CuentaBancariaService;
import service.ICuentaService;
import service.ServicioGUI;

/**
 *
 * @author sdlgv
 */
public class GUIActualizarCuentaAhorros extends javax.swing.JFrame implements ICambiable {

    ICuentaService service = CuentaBancariaService.getInstance();

    public GUIActualizarCuentaAhorros() {
        initComponents();
        setLocationRelativeTo(this);
        ServicioGUI.getInstance().registrarGUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMontoMinimoApertura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTasaInteres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInputNumCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Cuenta Ahorros");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel2.setText("Numero Cuenta:");
        jPanel1.add(jLabel2);

        txtNumCuenta.setEditable(false);
        txtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumCuenta);

        jLabel3.setText("Titular:");
        jPanel1.add(jLabel3);

        jPanel1.add(txtTitular);

        jLabel4.setText("Saldo:");
        jPanel1.add(jLabel4);

        txtSaldo.setEditable(false);
        jPanel1.add(txtSaldo);

        jLabel5.setText("Monto Minimo Apertura:");
        jPanel1.add(jLabel5);

        txtMontoMinimoApertura.setEditable(false);
        jPanel1.add(txtMontoMinimoApertura);

        jLabel6.setText("Tasa Interes:");
        jPanel1.add(jLabel6);

        jPanel1.add(txtTasaInteres);

        jLabel1.setText("Ingrese numero de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBuscar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtInputNumCuenta.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número");
                return;
            }
            int numBuscar = Integer.parseInt(txtInputNumCuenta.getText());
            CuentaBancaria cuentaGen = service.buscarPorNumero(numBuscar);

            if (cuentaGen instanceof CuentaAhorros && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {
                CuentaAhorros cuenta = (CuentaAhorros) cuentaGen;
                txtNumCuenta.setText(String.valueOf(cuenta.getNumeroCuenta()));
                txtTitular.setText(cuenta.getTitular());
                txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
                txtMontoMinimoApertura.setText(String.valueOf(cuenta.getMontoMinApertura()));
                txtTasaInteres.setText(String.valueOf(cuenta.getTasaInteres()));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada o no es de tipo Ahorros");
                limpiarCampos();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String numCuentaStr = txtNumCuenta.getText();
        if (numCuentaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe buscar una cuenta para actualizar.");
            return;
        }
        try {
            int numero = Integer.parseInt(numCuentaStr);
            String titular = txtTitular.getText();
            double tasaInteres = Double.parseDouble(txtTasaInteres.getText());

            int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea actualizar la cuenta de " + titular + "?",
                    "Confirmar actualización",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                service.actualizarCuentaAhorros(numero, titular, tasaInteres);
                ServicioGUI.getInstance().cambioEnGUI();
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta actualizada exitosamente.");
                limpiarCampos();
                txtInputNumCuenta.setText("");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Revisa que los campos numéricos sean correctos.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIActualizarCuentaAhorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInputNumCuenta;
    private javax.swing.JTextField txtMontoMinimoApertura;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTasaInteres;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables

    private void refrescarCuenta() {
        String numStr = txtNumCuenta.getText();
        if (!numStr.isEmpty()) {
            try {
                CuentaBancaria cuentaGen = service.buscarPorNumero(Integer.parseInt(numStr));
                if (cuentaGen instanceof CuentaAhorros && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {
                    CuentaAhorros cuenta = (CuentaAhorros) cuentaGen;
                    txtNumCuenta.setText(String.valueOf(cuenta.getNumeroCuenta()));
                    txtTitular.setText(cuenta.getTitular());
                    txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
                    txtMontoMinimoApertura.setText(String.valueOf(cuenta.getMontoMinApertura()));
                    txtTasaInteres.setText(String.valueOf(cuenta.getTasaInteres()));
                } else {
                    limpiarCampos();
                }
            } catch (Exception ex) {
                limpiarCampos();
            }
        }
    }

    private void limpiarCampos() {
        txtNumCuenta.setText("");
        txtTitular.setText("");
        txtSaldo.setText("");
        txtMontoMinimoApertura.setText("");
        txtTasaInteres.setText("");
    }

    @Override
    public void cambio() {
        refrescarCuenta();
    }
}
