/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.CuentaBancaria;
import model.CuentaAhorros;
import service.CuentaBancariaService;
import service.ICuentaService;

/**
 *
 * @author sdlgv
 */
public class GUIBuscarCuentaAhorros extends javax.swing.JFrame {

    /**
     * Creates new form GUIBuscarCuentaAhorros
     */
    private ICuentaService service;

    public GUIBuscarCuentaAhorros() {
        initComponents();
        setLocationRelativeTo(this);
        service = new CuentaBancariaService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMontoMinimoApertura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTasaInteres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInputNumCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Cuenta Ahorros");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel2.setText("Numero Cuenta:");
        jPanel1.add(jLabel2);

        txtNumCuenta.setEditable(false);
        txtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumCuenta);

        jLabel3.setText("Titular:");
        jPanel1.add(jLabel3);

        txtTitular.setEditable(false);
        jPanel1.add(txtTitular);

        jLabel4.setText("Saldo:");
        jPanel1.add(jLabel4);

        txtSaldo.setEditable(false);
        jPanel1.add(txtSaldo);

        jLabel5.setText("Monto Minimo Apertura:");
        jPanel1.add(jLabel5);

        txtMontoMinimoApertura.setEditable(false);
        jPanel1.add(txtMontoMinimoApertura);

        jLabel6.setText("Rendimiento:");
        jPanel1.add(jLabel6);

        txtTasaInteres.setEditable(false);
        jPanel1.add(txtTasaInteres);

        jLabel1.setText("Ingrese numero de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtInputNumCuenta.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número");
                return;
            }
            
            int numBuscar = Integer.parseInt(txtInputNumCuenta.getText());
            
            CuentaBancaria cuentaGen = service.buscarPorNumero(numBuscar);
            
            if (cuentaGen != null && cuentaGen instanceof CuentaAhorros && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {
                
                CuentaAhorros cuenta = (CuentaAhorros) cuentaGen;
                
                txtNumCuenta.setText(String.valueOf(cuenta.getNumeroCuenta()));
                txtTitular.setText(cuenta.getTitular());
                txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
                txtMontoMinimoApertura.setText(String.valueOf(cuenta.getMontoMinApertura()));
                txtTasaInteres.setText(String.valueOf(cuenta.getTasaInteres()));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada o no es de tipo Corriente");
                
                txtNumCuenta.setText("");
                txtTitular.setText("");
                txtSaldo.setText("");
                txtMontoMinimoApertura.setText("");
                txtTasaInteres.setText("");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBuscarCuentaAhorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInputNumCuenta;
    private javax.swing.JTextField txtMontoMinimoApertura;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTasaInteres;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
