/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.CuentaAhorros;
import model.CuentaBancaria;
import service.CuentaBancariaService;
import service.ICuentaService;

/**
 *
 * @author jaiderclavijo
 */
public class GUIDepositar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIDepositar.class.getName());

    /**
     * Creates new form GUIDepositar
     */
    private ICuentaService service = new CuentaBancariaService();
    public GUIDepositar() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInputNumCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtInputDepositar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Depositar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Depositar"));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 20, 50));

        jLabel2.setText("Numero Cuenta:");
        jPanel1.add(jLabel2);

        txtNumCuenta.setEditable(false);
        txtNumCuenta.addActionListener(this::txtNumCuentaActionPerformed);
        jPanel1.add(txtNumCuenta);

        jLabel3.setText("Titular:");
        jPanel1.add(jLabel3);

        txtTitular.setEditable(false);
        jPanel1.add(txtTitular);

        jLabel4.setText("Saldo:");
        jPanel1.add(jLabel4);

        txtSaldo.setEditable(false);
        jPanel1.add(txtSaldo);

        jLabel1.setText("Ingrese numero de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(this::btnDepositarActionPerformed);

        jLabel5.setText("Cantidad a Depositar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(txtInputDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDepositar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtInputDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try {
            if (txtInputNumCuenta.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número");
                return;
            }

            int numBuscar = Integer.parseInt(txtInputNumCuenta.getText());

            CuentaBancaria cuentaGen = service.buscarPorNumero(numBuscar);

            if (cuentaGen != null && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {


                txtNumCuenta.setText(String.valueOf(cuentaGen.getNumeroCuenta()));
                txtTitular.setText(cuentaGen.getTitular());
                txtSaldo.setText(String.valueOf(cuentaGen.getSaldo()));
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada=");

                txtNumCuenta.setText("");
                txtTitular.setText("");
                txtSaldo.setText("");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        String numCuentaStr = txtNumCuenta.getText();
        double monto = Double.parseDouble(txtInputDepositar.getText());

        if (numCuentaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe buscar una cuenta para depositar.");
            return;
        }

        int numero = Integer.parseInt(numCuentaStr);

        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea depositar en la cuenta de " + txtTitular.getText() + "?",
                "Confirmar deposito",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            service.depositar(numero,monto);
           
                javax.swing.JOptionPane.showMessageDialog(this, "Deposito realizado exitosamente.");
                txtNumCuenta.setText(String.valueOf(service.buscarPorNumero(numero).getNumeroCuenta()));
                txtTitular.setText(service.buscarPorNumero(numero).getTitular());
                txtSaldo.setText(String.valueOf(service.buscarPorNumero(numero).getSaldo()));
                txtInputNumCuenta.setText("");
                txtInputDepositar.setText("");
            
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIDepositar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInputDepositar;
    private javax.swing.JTextField txtInputNumCuenta;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
