/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.CuentaAhorros;
import model.CuentaBancaria;
import service.CuentaBancariaService;
import service.ICuentaService;

/**
 *
 * @author sdlgv
 */
public class GUIEliminarCuentaAhorros extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarCuentaAhorros
     */
    private ICuentaService service;

    public GUIEliminarCuentaAhorros() {
        initComponents();
        setLocationRelativeTo(this);
        service = new CuentaBancariaService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMontoMinimoApertura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTasaInteres = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtInputNumCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Cuenta ahorros");

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Cuenta Ahorros"));
        jPanel18.setToolTipText("");
        jPanel18.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel2.setText("Numero Cuenta:");
        jPanel18.add(jLabel2);

        txtNumCuenta.setEditable(false);
        txtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentaActionPerformed(evt);
            }
        });
        jPanel18.add(txtNumCuenta);

        jLabel3.setText("Titular:");
        jPanel18.add(jLabel3);

        txtTitular.setEditable(false);
        jPanel18.add(txtTitular);

        jLabel4.setText("Saldo:");
        jPanel18.add(jLabel4);

        txtSaldo.setEditable(false);
        jPanel18.add(txtSaldo);

        jLabel5.setText("Monto Minimo Apertura:");
        jPanel18.add(jLabel5);

        txtMontoMinimoApertura.setEditable(false);
        jPanel18.add(txtMontoMinimoApertura);

        jLabel6.setText("Tasa Interes:");
        jPanel18.add(jLabel6);

        txtTasaInteres.setEditable(false);
        jPanel18.add(txtTasaInteres);

        jLabel13.setText("Ingrese numero de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtInputNumCuenta.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número");
                return;
            }

            int numBuscar = Integer.parseInt(txtInputNumCuenta.getText());

            CuentaBancaria cuentaGen = service.buscarPorNumero(numBuscar);

            if (cuentaGen != null && cuentaGen instanceof CuentaAhorros && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {

                CuentaAhorros cuenta = (CuentaAhorros) cuentaGen;

                txtNumCuenta.setText(String.valueOf(cuenta.getNumeroCuenta()));
                txtTitular.setText(cuenta.getTitular());
                txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
                txtMontoMinimoApertura.setText(String.valueOf(cuenta.getMontoMinApertura()));
                txtTasaInteres.setText(String.valueOf(cuenta.getTasaInteres()));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada o no es de tipo Corriente");

                txtNumCuenta.setText("");
                txtTitular.setText("");
                txtSaldo.setText("");
                txtMontoMinimoApertura.setText("");
                txtTasaInteres.setText("");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String numCuentaStr = txtNumCuenta.getText();

        if (numCuentaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe buscar una cuenta para eliminar.");
            return;
        }

        int numero = Integer.parseInt(numCuentaStr);

        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar la cuenta de " + txtTitular.getText() + "?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            boolean eliminar = service.eliminar(numero);
            if (eliminar) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta eliminada exitosamente.");
                txtNumCuenta.setText("");
                txtTitular.setText("");
                txtSaldo.setText("");
                txtMontoMinimoApertura.setText("");
                txtTasaInteres.setText("");
                txtInputNumCuenta.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al intentar eliminar.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarCuentaAhorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JTextField txtInputNumCuenta;
    private javax.swing.JTextField txtMontoMinimoApertura;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTasaInteres;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
