/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.CuentaBancaria;
import model.CuentaCorriente;
import model.TarjetaCredito;
import service.CuentaBancariaService;
import service.ICuentaService;
import service.ServicioGUI;

/**
 *
 * @author sdlgv
 */
public class GUIGestionarTarjetaCredito extends javax.swing.JFrame implements ICambiable {

    ICuentaService service = CuentaBancariaService.getInstance();

    public GUIGestionarTarjetaCredito() {
        initComponents();
        setLocationRelativeTo(this);
        ServicioGUI.getInstance().registrarGUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCupo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCuotaManejo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtInputNumCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Tarjeta de Crédito");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)),
                "Datos de la Tarjeta"));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 20, 20));

        jLabel2.setText("Num Cuenta Corriente:");
        jPanel1.add(jLabel2);

        txtNumCuenta.setEditable(false);
        jPanel1.add(txtNumCuenta);

        jLabel3.setText("Titular:");
        jPanel1.add(jLabel3);

        txtTitular.setEditable(false);
        jPanel1.add(txtTitular);

        jLabel4.setText("Numero Tarjeta:");
        jPanel1.add(jLabel4);

        jPanel1.add(txtNumeroTarjeta);

        jLabel5.setText("Cupo:");
        jPanel1.add(jLabel5);

        jPanel1.add(txtCupo);

        jLabel6.setText("Cuota Manejo:");
        jPanel1.add(jLabel6);

        jPanel1.add(txtCuotaManejo);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)),
                "Listar Tarjetas de Crédito"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Num Cuenta", "Titular", "Num Tarjeta", "Cupo", "Cuota Manejo"
            }
        ) {
            boolean[] canEdit = new boolean [] {false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Ingrese numero de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminarTarjeta.setText("Eliminar Tarjeta");
        btnEliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarTarjeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminarTarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtInputNumCuenta.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número");
                return;
            }
            int numBuscar = Integer.parseInt(txtInputNumCuenta.getText());
            CuentaBancaria cuentaGen = service.buscarPorNumero(numBuscar);

            if (cuentaGen instanceof CuentaCorriente && cuentaGen.getEstado().equalsIgnoreCase("Activo")) {
                CuentaCorriente cuenta = (CuentaCorriente) cuentaGen;
                txtNumCuenta.setText(String.valueOf(cuenta.getNumeroCuenta()));
                txtTitular.setText(cuenta.getTitular());
                TarjetaCredito tarjeta = cuenta.getTarjetaCredito();
                if (tarjeta != null) {
                    txtNumeroTarjeta.setText(tarjeta.getNumeroTarjeta());
                    txtCupo.setText(String.valueOf(tarjeta.getCupo()));
                    txtCuotaManejo.setText(String.valueOf(tarjeta.getCuotaManejo()));
                } else {
                    txtNumeroTarjeta.setText("");
                    txtCupo.setText("");
                    txtCuotaManejo.setText("");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada o no es de tipo Corriente");
                limpiarCampos();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese solo números");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String numCuentaStr = txtNumCuenta.getText();
        if (numCuentaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe buscar una Cuenta Corriente.");
            return;
        }
        try {
            int numero = Integer.parseInt(numCuentaStr);
            String numTarjeta = txtNumeroTarjeta.getText().trim();
            double cupo = Double.parseDouble(txtCupo.getText());
            double cuotaManejo = Double.parseDouble(txtCuotaManejo.getText());

            if (numTarjeta.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El número de tarjeta no puede estar vacío.");
                return;
            }

            CuentaBancaria c = service.buscarPorNumero(numero);
            CuentaCorriente corriente = (CuentaCorriente) c;

            if (corriente.getTarjetaCredito() == null) {
                service.asociarTarjetaCredito(numero, numTarjeta, cupo, cuotaManejo);
                javax.swing.JOptionPane.showMessageDialog(this, "Tarjeta asociada exitosamente.");
            } else {
                service.actualizarTarjetaCredito(numero, numTarjeta, cupo, cuotaManejo);
                javax.swing.JOptionPane.showMessageDialog(this, "Tarjeta actualizada exitosamente.");
            }
            ServicioGUI.getInstance().cambioEnGUI();
            limpiarCampos();
            txtInputNumCuenta.setText("");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Revisa que los campos numéricos sean correctos.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTarjetaActionPerformed
        String numCuentaStr = txtNumCuenta.getText();
        if (numCuentaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debe buscar una Cuenta Corriente.");
            return;
        }
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar la tarjeta de " + txtTitular.getText() + "?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int numero = Integer.parseInt(numCuentaStr);
                service.eliminarTarjetaCredito(numero);
                ServicioGUI.getInstance().cambioEnGUI();
                javax.swing.JOptionPane.showMessageDialog(this, "Tarjeta eliminada exitosamente.");
                limpiarCampos();
                txtInputNumCuenta.setText("");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarTarjetaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarTarjetaCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGestionarTarjetaCredito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarTarjeta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCuotaManejo;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtInputNumCuenta;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<CuentaBancaria> todas = service.listar();
        for (CuentaBancaria cuenta : todas) {
            if (cuenta instanceof CuentaCorriente corriente && corriente.getTarjetaCredito() != null) {
                TarjetaCredito t = corriente.getTarjetaCredito();
                model.addRow(new Object[]{
                    corriente.getNumeroCuenta(),
                    corriente.getTitular(),
                    t.getNumeroTarjeta(),
                    t.getCupo(),
                    t.getCuotaManejo()
                });
            }
        }
    }

    private void limpiarCampos() {
        txtNumCuenta.setText("");
        txtTitular.setText("");
        txtNumeroTarjeta.setText("");
        txtCupo.setText("");
        txtCuotaManejo.setText("");
    }

    @Override
    public void cambio() {
        cargarTabla();
    }
}
