/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author sdlgv
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        miCrearAhorro = new javax.swing.JMenuItem();
        miBuscarAhorro = new javax.swing.JMenuItem();
        miEliminarAhorro = new javax.swing.JMenuItem();
        miListarAhorro = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miCrearCorriente = new javax.swing.JMenuItem();
        miBuscarCorriente = new javax.swing.JMenuItem();
        miEliminarCorriente = new javax.swing.JMenuItem();
        miListarCorriente = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Cuenta Ahorros");

        miCrearAhorro.setText("Crear Cuenta");
        miCrearAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearAhorroActionPerformed(evt);
            }
        });
        jMenu4.add(miCrearAhorro);

        miBuscarAhorro.setText("Buscar Cuenta");
        miBuscarAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarAhorroActionPerformed(evt);
            }
        });
        jMenu4.add(miBuscarAhorro);

        miEliminarAhorro.setText("Eliminar Cuenta");
        miEliminarAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarAhorroActionPerformed(evt);
            }
        });
        jMenu4.add(miEliminarAhorro);

        miListarAhorro.setText("Listar Cuentas");
        miListarAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarAhorroActionPerformed(evt);
            }
        });
        jMenu4.add(miListarAhorro);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Cuenta Corriente");

        miCrearCorriente.setText("Crear Cuenta");
        miCrearCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearCorrienteActionPerformed(evt);
            }
        });
        jMenu5.add(miCrearCorriente);

        miBuscarCorriente.setText("Buscar Cuenta");
        miBuscarCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarCorrienteActionPerformed(evt);
            }
        });
        jMenu5.add(miBuscarCorriente);

        miEliminarCorriente.setText("Eliminar Cuenta");
        miEliminarCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEliminarCorrienteActionPerformed(evt);
            }
        });
        jMenu5.add(miEliminarCorriente);

        miListarCorriente.setText("Listar Cuentas");
        miListarCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarCorrienteActionPerformed(evt);
            }
        });
        jMenu5.add(miListarCorriente);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCrearAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearAhorroActionPerformed
        GUICrearCuentaAhorro c = new GUICrearCuentaAhorro();
        c.setVisible(true);
    }//GEN-LAST:event_miCrearAhorroActionPerformed

    private void miBuscarAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarAhorroActionPerformed
        GUIBuscarCuentaAhorros c = new GUIBuscarCuentaAhorros();
        c.setVisible(true);
    }//GEN-LAST:event_miBuscarAhorroActionPerformed

    private void miEliminarAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarAhorroActionPerformed
        GUIEliminarCuentaAhorros c = new GUIEliminarCuentaAhorros();
        c.setVisible(true);
    }//GEN-LAST:event_miEliminarAhorroActionPerformed

    private void miListarAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarAhorroActionPerformed
        GUIListarAhorros c = new GUIListarAhorros();
        c.setVisible(true);
    }//GEN-LAST:event_miListarAhorroActionPerformed

    private void miCrearCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearCorrienteActionPerformed
        GUICrearCuentaCorriente c = new GUICrearCuentaCorriente();
        c.setVisible(true);
    }//GEN-LAST:event_miCrearCorrienteActionPerformed

    private void miBuscarCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarCorrienteActionPerformed
        GUIBuscarCuentaCorriente c = new GUIBuscarCuentaCorriente();
        c.setVisible(true);
    }//GEN-LAST:event_miBuscarCorrienteActionPerformed

    private void miEliminarCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEliminarCorrienteActionPerformed
        GUIEliminarCuentaCorriente c = new GUIEliminarCuentaCorriente();
        c.setVisible(true);
    }//GEN-LAST:event_miEliminarCorrienteActionPerformed

    private void miListarCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarCorrienteActionPerformed
        GUIListarCorriente c = new GUIListarCorriente();
        c.setVisible(true);
    }//GEN-LAST:event_miListarCorrienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miBuscarAhorro;
    private javax.swing.JMenuItem miBuscarCorriente;
    private javax.swing.JMenuItem miCrearAhorro;
    private javax.swing.JMenuItem miCrearCorriente;
    private javax.swing.JMenuItem miEliminarAhorro;
    private javax.swing.JMenuItem miEliminarCorriente;
    private javax.swing.JMenuItem miListarAhorro;
    private javax.swing.JMenuItem miListarCorriente;
    // End of variables declaration//GEN-END:variables
}
